### ISSUE TITLE
molecule-ec2 plugin code was not add to the repo

### ISSUE THREAD

**Issue by tbugfinder** [ansible-community/molecule-ec2#1]
Hi,
following molecule changelog I got to this repo. Now I'm wondering why it is empty....

**Comment by ssbarnea** [comment]
@tbugfinder Mainly because I did not find time to finish the migration for all plugins, in fact only few are done. Another reason for delaying was that I did not have any user interested about these plugins, are you willing to assist me finishing the move?

**Comment by tbugfinder** [comment]
How could I help?

**Comment by jonashackt** [comment]
Would be also interested in this plugin, since I use it for some example projects and blog posts (which need to be updated too) 😃

**Comment by mohitkumarsharmaflux7** [comment]
we are highly using molecule-ec2 and deligated drivers , so you guys can also migrate these 2 to new molecule version 3, let me know if I can help in any way.

**Comment by mohitkumarsharmaflux7** [comment]
@ssbarnea
